name: 'JSON Read Test'
description: 'Test JSON Read'
inputs:
  config:
    description: 'Config file name'
    required: true
    default: ''
outputs:
  test:
    description: 'The example param'
runs:
  using: 'node16'
  main: 'index.js'
